#!/usr/bin/env sh
function log() {
  echo "=== $1 ==="
}

setup

USER=$1
GROUP=$2
WORKLOAD=$3
shift 3

mkdir handler

log "Compiling Handler"
if ! do_transform.py < scripts/handler.py > handler/handler_transformed.py
  then
    exit $?
fi

log "Running Coordinator"
mkdir -p out/$WORKLOAD
cd out/$WORKLOAD

LOGGING_DIR=`date '+%Y-%m-%d_%H:%M:%S'`_`cat /proc/sys/kernel/random/uuid`
coordinator "${@}" --name=$WORKLOAD --log-dir=$LOGGING_DIR /root/handler/handler_transformed.py /root/scripts/* /root/compiler/rt/

if [ -d "/root/out/$WORKLOAD/$LOGGING_DIR" ]
  then
    chown -R $USER:$GROUP /root/out/$WORKLOAD/$LOGGING_DIR
    log "Logs for this run can be found in $LOGGING_DIR"
fi

chown -R $USER:$GROUP /root/.aws
